### ISSUE TITLE
Monitorowanie powiadomień z oficjalnej apki

### ISSUE THREAD

**Issue by TheLastGimbus** [wulkanowy/wulkanowy#1043]
Korzytam ze [Slide](https://github.com/ccrama/Slide), open source klienta do Reddita, i jest w nim opcja "Notification piggybacking":

![Screenshot_20201209-115232_Slide](https://user-images.githubusercontent.com/40139196/101621026-27b39b00-3a0d-11eb-8224-e9a2afb40e53.png)

Ponieważ (chyba) nie da sie/nie wolno nam podpinać sie do tego samego FCM co oficjalna apka (a na pewno nie w F-droidowej wersji), trzeba po prostu sprawdzać dane z serwera co jakiś czas (~15 min, ale Android może to wydłużyć :confused:)

Slide prosi o uprawnienie do monitorowania powiadomień, i odświeża dane z serwera wtedy, kiedy oficjalna apka coś dostanie - działa to bardzo spoko :+1: 

Może moglibyśmy coś podobnego tutaj zrobić?

**Comment by Zaptyp** [comment]
A po co to komu?

**Comment by Zaptyp** [comment]
Bo nie wiem do czego można to konkretnie użyć.

**Comment by mklkj** [comment]
> A po co to komu?

@Zaptyp dzięki temu Wulkanowy mógłby (tak jakby) obsługiwać natychmiastowe powiadomienia. Tylko wymagałoby to zainstalowanej oficjalnej aplikacji.

@TheLastGimbus myślę, że moglibyśmy coś takiego zrobić w Wulkanowym

#760

**Comment by Faierbel** [comment]
https://github.com/Chagall/notification-listener-service-example
https://github.com/ccrama/Slide/blob/master/app/src/main/java/me/ccrama/redditslide/Notifications/NotificationPiggyback.java
