### ISSUE TITLE
Unable to log in using GPE

### ISSUE THREAD

**Issue by gbaranski** [wulkanowy/wulkanowy#1044]
## Co powinno się dziać
Successful sign in using GPE

## Co się dzieje
Logging in throws invalid credentials error.
Credentials are valid for sure, tested on the web version and it works correctly.

## Jak to zrobić kolejny raz:
  1. Log in using GPE Account

## Informacje o urządzeniu i dzienniku
  - Wersja aplikacji: 0.22.2
  - Wersja Androida: 11
  - Adres URL dziennika: https://aplikacje.edu.gdansk.pl/

Recently GPE changed their login site, so that could be because of that.
Running `adb logcat` doesn't show any info in the production build.

**Comment by mklkj** [comment]
@gbaranski please update to last version ([0.23.0](https://github.com/wulkanowy/wulkanowy/releases/tag/0.23.0))

**Comment by gbaranski** [comment]
> @gbaranski please update to latest version ([0.23.0](https://github.com/wulkanowy/wulkanowy/releases/tag/0.23.0))

Thanks, reinstallation was required and now it works fine 😃
