### ISSUE TITLE
Ekran startowy (à la dashboard)

### ISSUE THREAD

**Issue by mklkj** [wulkanowy/wulkanowy#1054]
Ekran startowy uruchamiałby się po zalogowaniu/po starcie aplikacji.

Na głównym ekranie znajdowałyby się karty ze skrótem najważniejszych informacji, np.:
- szczęśliwy numerek
- ostatnie oceny
- bieżąca/następna lekcja
- ostatnie wiadomości
- prace domowe do zrobienia
- nadchodzące sprawdziany
- zbliżające się zebrania z rodzicami
- komunikaty dyrektora #1015 
- ~~reklamy~~

Docelowo karty można byłoby usuwać/dodawać/przestawiać.

Do dyskusji:
- jakie karty w pierwszej kolejności powinniśmy przygotować i jakie dokładnie informacje powinny zawierać oraz jakie miejsca powinny być klikalne i gdzie dokładnie przekierowywać
- czy robimy na tym ekranie *swipe to refresh*? Jeśli tak, to czy odświeżamy wtedy tylko dane, które wyświetlać się mogą na tym ekranie, czy odpalamy synchronizację (np. to samo co robi przycisk "Synchronizuj teraz" w ustawieniach)

**Comment by Daxxxis** [comment]
Koncepcja wyglądu
![Screenshot_2020-04-02-00-55-02-327_io github wulkanowy feature_homework_mark_as_done](https://user-images.githubusercontent.com/60961958/102760383-b8776880-4375-11eb-8c9d-0333cd4d7697.jpg)

**Comment by Daxxxis** [comment]
Druga koncepcja wyglądu
![dashboard-1](https://user-images.githubusercontent.com/60961958/110261743-a9d24200-7fb1-11eb-99da-be49ed1622d7.jpg)
