### ISSUE TITLE
Nie ładujące się nazwy lekcji

### ISSUE THREAD

**Issue by miki164** [wulkanowy/wulkanowy#1222]
![Screenshot_20210316_101257_io.github.wulkanowy.jpg](https://user-images.githubusercontent.com/32245772/111284256-3f1fa700-8640-11eb-8e79-e7830e4d29e9.jpg)

**Comment by mklkj** [comment]
@miki164 to już jest naprawione w wersji 1.1.1. Pobierz aktualizację

Duplicate of #1218
