### ISSUE TITLE
Dodanie przeźroczystości do widgeta

### ISSUE THREAD

**Issue by 1116574** [wulkanowy/wulkanowy#1236]
Dodanie przeźroczystego tła w widgecie, tak aby było przez niego widać tapetę. Przykład: [na discordzie](https://discordapp.com/channels/390889354199040011/529025688238424077/822457256985624617)

**Comment by Daxxxis** [comment]
Efekt przezroczystości został dodany do widżetu planu lekcji w wersji 1.2, przydałoby się zrobić podobnie z widżetem szczęśliwego numerka
