### ISSUE TITLE
Poprawki w powiadomieniach o sprawdzianach i zadaniach domowych

### ISSUE THREAD

**Issue by mklkj** [wulkanowy/wulkanowy#1273]
- [x] dodać brakujący content w zwiniętym powiadomieniu
- [x] dodać daty dla danego wydarzenia (bo teraz wiadomo tylko że się coś pojawiło, ale nie wiadomo kiedy)
- [x] naprawić pending intent w powiadomieniach, bo teraz mają taki sam request code (MainView.Section.MESSAGE.id), przez co przekierowanie po kliknięciu może dawać nieoczekiwane rezultaty
- [x] odfiltrowywanie powiadomień o minionych wydarzeniach

Related #1243

**Comment by Daxxxis** [comment]
Powiadomienia dodatkowo przychodzą ze sprawdzianami i zadaniami, które już minęły. Trzeba dodać sprawdzanie daty
