### ISSUE TITLE
Wyświetlanie statusu przeczytania wiadomości przez adresata w podglądzie wiadomości

### ISSUE THREAD

**Issue by mklkj** [wulkanowy/wulkanowy#1288]
> Dzień dobry, mam pytanie czy można dodać do aplikacji mobilnej w dzienniku Wulkanowy, opcje aby na telefonie było można sprawdzić czy np. nauczyciel odczytał ode mnie wiadomość. Tak samo jak jest na komputerze.

**Comment by Daxxxis** [comment]
Duplicate of #800
