### ISSUE TITLE
Dodanie funkcji, która wysyła usprawiedliwienie do wychowawczyni 

### ISSUE THREAD

**Issue by MRmlik12** [wulkanowy/wulkanowy#1290]
** Czy Twoja prośba o funkcję jest związana z problemem? Proszę opisz.**
Dla rodziców taki system będzie super opcją, która zaoszczędzi czas pisania usprawiedliwienia, gdzie ich córka/syn są często zwolnieni z zajęć lekcyjnych.

** Opisz żądane rozwiązanie **
Rozwiązanie ma działać na systemie szablonów np.lekarz, a w nim narzędzia ułatwiające automatyzację szablonów np, dodanie słów kluczowych data, godzina lekcyjna itd. Prawdopodobnie będzie to umieszczone w frekwencji lub wiadomościach.

**Comment by studzinskik** [comment]
Dialog z polem tekstowym na powód i podgląd wiadomości, uzupełnianie w oparciu o uniwersalny template
```
Dzień dobry,
Proszę o usprawiedliwienie nieobecności mojego dziecka w [dniu/dniach] [lista dni, ewentualnie każdy dzień poprzedzony tekstem (cały dzień) lub np. (1, 2 i 3 lekcja)] {z powodu [tekst z pola tekstowego], jeśli pole tekstowe nie jest puste}

Pozdrawiam,
[Imię i nazwisko wysyłającego]
```
