### ISSUE TITLE
Wyświetlanie nazwiska nauczyciela w szczegółach lekcji w planie zajęć

### ISSUE THREAD

**Issue by TheLastGimbus** [wulkanowy/wulkanowy#1337]
** Czy Twoja prośba o funkcję jest związana z problemem? Proszę opisz.**
Chodze do mojej szkoły od dwóch lat, i dalej nie pamiętam nazwisk nauczycieli :P

** Opisz żądane rozwiązanie **
W planie lekcji, gdy kliknie się na jakąś lekcje, wyświetla się sala, grupa, i godziny, ale brakuje nazwiska nauczyciela. Byłoby super gdyby tam było!

**Comment by mklkj** [comment]
Hej! To jest ogólnie jeden ze starszych problemów. Opiszę pokrótce na czym polega problem:
1. Wulkanowy pobiera dane ze strony www dziennika UONET+
2. Strona www dziennika UONET+ w zakładce Plan zajęć nie zawiera nazwisk nauczycieli przy lekcjach
3. Wulkanowy nie wyświetla nazwisk nauczycieli bo ich tam nie ma.

Nie dzieje się tak zawsze, bo czasami nauczyciele jednak są tam wpisani, wtedy Wulkanowy potrafi ich wyświetlić.
W aplikacji pojawiały się próby obejścia tej niedogodności (#485), ale to ogranicza problem tylko wtedy, gdy te informacje zniknęły zanim lekcja się odbyła, a nie gdy ich nie było ich nigdy.

**Comment by TheLastGimbus** [comment]
:thinking:  no faktycznie troche lipa

Zakładka "More->School and teachers" ma wszystkich nauczycieli i przedmioty których uczą - tylko penwie poderzewam że brakuje danych czy dany nauczyciel mnie uczy :confused: 

Gdyby dało sie nawet lokalnie wybrać raz ręcznie kto uczy czego żeby potem mieć szybką ściągawke to by było fajne, chociaż rozumiem że to pół środek i może sie nawet nie opłacać tego pisać...

**Comment by Faierbel** [comment]
Do zrobienia:
Dodanie nauczyciela do szczegółów lekcji na podstawie listy nauczyieli porównując nazwy przedmiotów

Nie jest pewne rozwiązanie
Zrobić jako ustawienie (???)

**Comment by Daxxxis** [comment]
Częściowo łączy się to z #1465

**Comment by mklkj** [comment]
Prawdopodobnie permanentnie rozwiązane aktualizacją 21.11.0.28 systemu UONET+ (poprawka z pomieszanymi numerami sal i nauczycielami w wydaniu 1.2.3)

**Comment by TheLastGimbus** [comment]
Umm ja dalej nie widze nazwisk w szczegółach...

**Comment by mklkj** [comment]
@TheLastGimbus Jaka odmiana dziennika?

**Comment by TheLastGimbus** [comment]
Resman Rzeszowski

**Comment by mklkj** [comment]
Aktualizacja wskoczyła niecałą dobę temu na vulcan.net.pl, pod innymi domenami pewnie pojawi się niebawem.
Wersja UONET+ na której nazwiska powinny być już zawsze widoczne to 21.10.0004.46546
