### ISSUE TITLE
Dodanie szuflady nawigacyjnej

### ISSUE THREAD

**Issue by Marioneq** [wulkanowy/wulkanowy#1416]
Mogła być by podobna do tej która jest w wulkanowym web
![image](https://user-images.githubusercontent.com/81989372/127775283-364db9a3-c576-49f9-aa14-68e7f432d726.png)

**Comment by mklkj** [comment]
Duplicate of #520

Mieliśmy w planach migrację z bottom navigation na drawera, ale uznaliśmy, że lepiej jest zostać z nawigacją dolną - coraz więcej popularnych aplikacji używa nawigacji poziomej zamiast bocznej, użytkownicy są do takich przyzwyczajeni, łatwiej się używa aplikacji z takim typem nawigacji (łatwiejszy dostęp przy do podstawowych funkcji przy trzymaniu smartfona jedną ręką), co przy rosnących rozmiarach wyświetlaczy jest jak najbardziej zrozumiałe.

**Comment by Pengwius** [comment]
Ewentualnie można by pomyśleć o przyszłym dodaniu wyboru pomiędzy bottom navem, a drawerem w ustawieniach, zawsze to jakieś urozmaicenie w aplikacji.

**Comment by mklkj** [comment]
Moim zdaniem nie ma sensu. W żadnej apce nie spotkałem się z takim rozwiązaniem, a i prawdopodobnie mało kto by z tej opcji skorzystał. Więc - pracy nie tak mało, a zysk niewielki
