### ISSUE TITLE
"Wystąpił nieoczekiwany błąd" nie ładuje zakładek w module oceny.

### ISSUE THREAD

**Issue by Zaptyp** [wulkanowy/wulkanowy#1488]
## Co powinno się dziać
"Wystąpił nieoczekiwany błąd" powinien razem pojawiać się z zakładkami na górze (Szczegóły, Podsumowanie, Klasa)

## Co się dzieje
"Wystąpił nieoczekiwany błąd" nie ładuje się z tymi zakładkami.

## Jak to zrobić kolejny raz:

1. Wejść do Android Debug Database
2. Wybrać wulkanowy-database
3. Wybrać tabelke Students
4. Wybrać wartość fakelog.cf
5. Zedytować
6. Dodać 2 literki d przed znakami ==
7. Uruchomić ponownie aplikacje
8. Przejść na moduł oceny

## Informacje o urządzeniu i dzienniku
- Wersja aplikacji: 5688-bugfix/timetable-error-view-fdroid (CHYBA dla wszystkich wersji DEV)
- Wersja Androida: 11
- Adres URL dziennika: Nie dotyczy

**Comment by Zaptyp** [comment]
![Screenshot_20210906-181121](https://user-images.githubusercontent.com/43276401/132243444-9f71fe6c-604c-4a68-8872-ad5b57a166a3.png)

**Comment by Faierbel** [comment]
Jest to prawidłowe zachowanie aplikacji. Błąd wystąpił podczas pobierania aktualnego studenta lub aktualnego semestru. Bez tyych danych widok z tabami się nie wyświetli
