### ISSUE TITLE
Mylący tekst w dashboardzie

### ISSUE THREAD

**Issue by dominik-korsa** [wulkanowy/wulkanowy#1515]
## Co się dzieje

![IMG_20210915_000751.jpg](https://user-images.githubusercontent.com/29484605/133340615-4e11793b-c8ca-46d2-90b5-18a51daa5165.jpg)

Tekst `dodatkowe lekcje` może wprowadzać w błąd, sugerując, że chodzi o lekcje "nieobowiązkowe"

## Informacje o urządzeniu i dzienniku:
Wulkanowy 1.2.2 Sklep Play
Fakelog

**Comment by dominik-korsa** [comment]
https://crowdin.com/translate/wulkanowy2/26/en-pl#2499

**Comment by Daxxxis** [comment]
Odpowiednie poprawki zostały dodane do pozostałych języków
