### ISSUE TITLE
Zmiany w planie na ekranie startowym

### ISSUE THREAD

**Issue by rekin5320** [wulkanowy/wulkanowy#1523]
Myślę, że przydatną rzeczą byłoby dodanie kafelka na ekranie startowym pokazującego ewentualne zmiany w planie takie jak zastępstwa lub odwołane lekcje. Nie trzeba by wtedy patrzeć na cały plan, żeby zobaczyć, czy są jakieś zmiany.

**Comment by Faierbel** [comment]
Nie widzimy tej funkcji w aplikacji. Więcej szczegółów https://discord.com/channels/390889354199040011/558394066505826304/909155788226953266
