### ISSUE TITLE
Dostosowanie aplikacji dla WSA

### ISSUE THREAD

**Issue by Daxxxis** [wulkanowy/wulkanowy#1603]
W związku z pojawieniem się Podsystemu Windows dla systemu Android™, można dostosować wszystkie widoki do wyświetlania się na dużych ekranach.
Niżej zostaną wymienione sugestie dotyczące owych ulepszeń. Lista będzie aktualizowana z biegiem pojawiających się nowych propozycji. 

Propozycje dostosowań:

- **Aplikacja**
Navigation rail lub navigation drawer zamiast bottom navigation 

- **Dashboard**
Kafelki wyświetlane w dwóch rzędach

- **Oceny**
Brak aktualnych sugestii 

- **Frekwencja, podsumowanie frekwencji**
Brak aktualnych sugestii 

- **Plan lekcji, lekcje dodatkowe i zrealizowane**
Widok tygodnia 

- **Wiadomości**
Widok listy wiadomości oraz treść wiadomości na podzielonym ekranie 

- **Sprawdziany, zadania domowe**
Brak aktualnych sugestii 

- **Uwagi i osiągnięcia, zebrania, ogłoszenia szkolne, historia szczęśliwego numerka, dostęp mobilny**
Brak aktualnych sugestii 

- **Szczęśliwy numerek**
Ukrycie tego menu, nie jest potrzebne wyświetlanie jednego numeru na całym ekranie 

- **Szkoła i nauczyciele**
Podzielony widok zamiast tabów

- **Szczegóły konta**
Podzielony widok

- **Ustawienia**
Podzielony widok
![jUXIS.png](https://user-images.githubusercontent.com/60961958/138635812-0950a945-b93c-45ce-a9d5-ca2d2b64e52e.png)

**Comment by mklkj** [comment]
Trochę już minęło, a teraz wygląda na to, że... WSA idzie do piachu: https://learn.microsoft.com/en-gb/windows/android/wsa/

> Microsoft is ending support for the Windows Subsystem for Android™️ (WSA). As a result, the Amazon Appstore on Windows and all applications and games dependent on WSA will no longer be supported beginning March 5, 2025. Until then, technical support will remain available to customers.
Customers that have installed the Amazon Appstore or Android apps prior to March 5, 2024, will continue to have access to those apps through the deprecation date of March 5, 2025. Please reach out to our support team for further questions at [support.microsoft.com](https://support.microsoft.com/). We are grateful for the support of our developer community and remain committed to listening to feedback as we evolve experiences.

W związku z tym sens robienia czegoś, czego za rok nie będzie się już dało używać uważam za nikły, a aplikacji na tablety raczej nie chcemy utrzymywać, dlatego zamykam
