### ISSUE TITLE
Sortowanie kafelka ostatnich ocen oraz zadań domowych

### ISSUE THREAD

**Issue by JelNiSlaw** [wulkanowy/wulkanowy#1611]
Oceny w kafelku Ostatnie oceny w Dashboardzie nie są sortowany według daty dodania.

**Comment by Daxxxis** [comment]
Podobna sytuacja jest w zadaniach domowych
![Screenshot_20211109-020726_Wulkanowy_DEV_5998.png](https://user-images.githubusercontent.com/60961958/140843014-e05e55bd-a8bb-4cae-b017-ed62abff36fd.png)
