### ISSUE TITLE
Splash screen obsługujący jasny i ciemny motyw 

### ISSUE THREAD

**Issue by Daxxxis** [wulkanowy/wulkanowy#1625]
![Screenshot_20211104-162623_Sklep_Google_Play.png](https://user-images.githubusercontent.com/60961958/140353915-47deefec-dacc-4ae8-aabf-d266337bd59f.png)
![Screenshot_20211104-162021_Sklep_Google_Play.png](https://user-images.githubusercontent.com/60961958/140354099-00c0dafb-2dcf-49dc-9822-d6ef08998406.png)

**Comment by Faierbel** [comment]
Nie zmieniamy aktualnego stylu splash screena więc czerwony zostanie dlaw wersji ciemnej i jasnej
