### ISSUE TITLE
Filtrowanie wiadomości od wielu placówek po skróconej nazwie szkoły 

### ISSUE THREAD

**Issue by Daxxxis** [wulkanowy/wulkanowy#1626]
![Screenshot_20211105-141629_Wulkanowy.png](https://user-images.githubusercontent.com/60961958/140516110-15091efb-3ba3-434f-9e46-022d1ef26424.png)

**Comment by mklkj** [comment]
Filtrowanie będziemy mieli teraz "out of the box" po wprowadzeniu wsparcia dla nowego modułu wiadomości.

Resolves #1945
