### ISSUE TITLE
Po wpisaniu przez nauczyciela lekcji zrealizowanej, powiadomienie o zmianie w lekcji przychodzi ponownie

### ISSUE THREAD

**Issue by Daxxxis** [wulkanowy/wulkanowy#1679]
Najprawdopodobniej znika pole ze starym, przekreślonym nauczycielem. Możliwe, że dzieje się tak podobnie z innymi polami (sala, przedmiot, grupa)

**Comment by mklkj** [comment]
Czy ktoś miał w roku szkolnym 2022/2023 podobny problem? Jeśli tak, proszę o otworzenie issue ponownie
