### ISSUE TITLE
Wulkanowy przesuwa liczbę punktów w lewo podczas każdego odświeżenia podczas przebywania w module UWAGI

### ISSUE THREAD

**Issue by Zaptyp** [wulkanowy/wulkanowy#1703]
## Co powinno się dziać
Wulkanowy nie powinna przesuwać liczby punktów w lewo podczas każdego odświeżenia

## Co się dzieje
Wulkanowy przesuwa liczby punktów w lewo podczas każdego odświeżenia i chyba to tylko dzieje się podczas zalogowania do dziennika vulcan.net.pl bo na fakelogu nie zarejestrowałem tego zjawiska
Nagranie zostanie wysłane tylko na prośbę maintenerów.

## Jak to zrobić kolejny raz:
Odświeżać listę uwag pociągnięciem w dół
## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: 1.4.3 i DEV 6113
  - Wersja Androida: 11
  - Adres URL dziennika: vulcan.net.pl/zielonagora

**Comment by Zaptyp** [comment]
Bug dalej występuje na wersji 1.6.3

**Comment by Faierbel** [comment]
A czy go zamknęliśmy żeby o tym przypominać ?
