### ISSUE TITLE
Naprawa przeglądarki do przeglądania licencji.

### ISSUE THREAD

**Issue by Zaptyp** [wulkanowy/wulkanowy#1707]
## Co powinno się dziać
Przeglądarka do przeglądania licencji powinna działać prawidłowo

## Co się dzieje
Przeglądarka do przeglądania licencji nie działa prawidłowo bo nie wyświetla dat i duplikuje wpisy

## Jak to zrobić kolejny raz:
Wystarczy po prostu wejść do przeglądarki służącej do przeglądania licencji
## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: 1.4.3
  - Wersja Androida: 11
  - Adres URL dziennika:

**Comment by Zaptyp** [comment]
![Screenshot_20211207-220336_Wulkanowy.png](https://user-images.githubusercontent.com/43276401/145105847-477d0d30-e245-45a4-9314-554f31c3f914.png)![Screenshot_20211207-220327_Wulkanowy.png](https://user-images.githubusercontent.com/43276401/145105852-7d81e07f-0b0e-4975-b733-b6104d7a9bab.png)![Screenshot_20211207-220318_Wulkanowy.png](https://user-images.githubusercontent.com/43276401/145105860-17242165-ac88-4237-9a2a-dd2654e16349.png)

**Comment by Zaptyp** [comment]
![Screenshot_20211207-220415_Wulkanowy.png](https://user-images.githubusercontent.com/43276401/145105983-00aaf32f-4975-439d-803b-0f4775356c28.png)![Screenshot_20211207-220447_Wulkanowy.png](https://user-images.githubusercontent.com/43276401/145105990-474a95d2-59cd-4166-8505-fd05eaaed22b.png)![Screenshot_20211207-220451_Wulkanowy.png](https://user-images.githubusercontent.com/43276401/145105996-be97cbfc-5d77-49ce-b557-6468e17f7142.png)

**Comment by Faierbel** [comment]
Lista bibliotek jest generowana przez inną libkę. Nie jest to duży błąd a napewno czasochłonny bo musielibyśmy wszystko manulanie robić dlatego zostawimy to tak jak jest.
