### ISSUE TITLE
Zapisywanie w bazie emalia zwróconego przez serwer

### ISSUE THREAD

**Issue by JelNiSlaw** [wulkanowy/wulkanowy#1751]
Podczas logowania, Wulkanowy zapisuje w bazie danych email (lub login) wpisany przez użytkownika, który może różnić się od tego używanego przez serwer (głównie wielkością liter).

[Dyskusja na Discordzie](https://discord.com/channels/390889354199040011/558341774704115713/930203558178074684)

**Comment by mklkj** [comment]
W zasadzie rozwiązane w https://github.com/wulkanowy/sdk/commit/3b25f5d9bfcb3dd82b65476a1af96e8d27b5b1f2#diff-6bd06196ef3dd129e77b38842b2855a816ab27563dccf9c3c5e78e31fe397fb6R214-R215

Aplikacja już teraz używa emaila (w którym to polu może znajdować się też login w przypadku innych odmian) zwróconego przez SDK https://github.com/wulkanowy/sdk/commit/3b25f5d9bfcb3dd82b65476a1af96e8d27b5b1f2#diff-6bd06196ef3dd129e77b38842b2855a816ab27563dccf9c3c5e78e31fe397fb6R214-R215
