### ISSUE TITLE
Zdalne dodawanie obsługi błędu w Wulkanowym

### ISSUE THREAD

**Issue by Zaptyp** [wulkanowy/wulkanowy#1762]
Pomysł dał użytkownik @doteq 
![Screenshot_20220122-120722_Discord.png](https://user-images.githubusercontent.com/43276401/150636034-0c2f486e-336e-441d-990c-a0bbcde8a6d8.png)

**Comment by mklkj** [comment]
wątek pojawił się też później https://discord.com/channels/390889354199040011/529025688238424077/916282737483206736

podsumowując: nie ma na tyle awarii, żeby bez wątpienia opłacało się inwestować w to nasz ograniczony czas
