### ISSUE TITLE
Wulkanowy pokazuje dziwne średnie w drugim semestrze

### ISSUE THREAD

**Issue by Zaptyp** [wulkanowy/wulkanowy#1763]
## Co powinno się dziać
Wulkanowy nie powinien pokazywać średnich w drugim semestrze jak nie ma ocen

## Co się dzieje
Wulkanowy bierze informacje nie wiadomo z skąd jak w dzienniku takich średnich nie ma
![Screenshot_20220111-075744_Wulkanowy.png](https://user-images.githubusercontent.com/43276401/150636600-7a492236-d255-44ed-9269-f542e689425d.png)
https://discord.com/channels/390889354199040011/499273409306427406/930354904881594388
## Jak to zrobić kolejny raz:

  1. Uruchomić Wulkanowego
  2. Wybrać zakładkę Oceny
  3. Zmienić semestr na drugi

## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: 1.5.0 
  - Wersja Androida: 11
  - Adres URL dziennika: Chyba wszystkie odmiany dziennika

**Comment by studzinskik** [comment]
![Screenshot_20220111-085446_Wulkanowy.jpg](https://user-images.githubusercontent.com/48914870/150638113-45be6f99-4d10-4cc8-8900-3271d9aac222.jpg)

![Screenshot_20220111-085450_Wulkanowy.jpg](https://user-images.githubusercontent.com/48914870/150638116-807290f4-dc96-4fae-955f-31c84b2bcb58.jpg)

Nie ma ocen do wyliczenia średniej (nie ma przez co podzielić)
