### ISSUE TITLE
Wulkanowy on iOS

### ISSUE THREAD

**Issue by Crunnie** [wulkanowy/wulkanowy#1788]
It sucks how bad the official one is, and I've tried Wulkanowy on an Android phone before. Any chance you could make an IPA version?

Highly appreciated. Thanks.

**Comment by Pengwius** [comment]
> It sucks how bad the official one is, and I've tried Wulkanowy on an Android phone before. Any chance you could make an IPA version?
> 
> Highly appreciated. Thanks.

Hi @Crunnie ! Wulkanowy is native app - it means, that app was writed specificly for one platform and you can't run it on other platform, but @v0idzz is creating his own app - Vulcanowa - which is hybrid app, so it's no problem to run it on android and iOS.

**Comment by mklkj** [comment]
Related #249
