### ISSUE TITLE
Dodatkowe Sprawdziany (m.in Poprawy)

### ISSUE THREAD

**Issue by AndusDEV** [wulkanowy/wulkanowy#1841]
**Czy Twoja prośba o funkcję jest związana z problemem? Proszę opisz.**
Mój pomysł to dodatkowe sprawdziany. M.in poprawy, lub sprawdziany nie wpisane przez nauczycieli.

**Opisz żądane rozwiązanie**
Można by dodać przycisk jak w planie lekcji z dodatkowymi lekcjami

**Opisz alternatywy, które rozważałeś**
Brak

**Dodatkowy kontekst**
Brak

**Comment by sadcenter** [comment]
#1670

**Comment by mklkj** [comment]
Duplicated #1670
