### ISSUE TITLE
Switching between accounts duplicates SchoolAnnouncements

### ISSUE THREAD

**Issue by mibac138** [wulkanowy/wulkanowy#1867]
https://user-images.githubusercontent.com/5672750/169714275-ff99c83a-8389-4d3f-886e-465b9405bd12.mp4

## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: 1.6.4
  - Wersja Androida: Emulator API 32
  - Adres URL dziennika: fakelog

**Comment by Faierbel** [comment]
https://github.com/wulkanowy/wulkanowy/blob/develop/app/src/main/java/io/github/wulkanowy/data/mappers/DirectorInformationMapper.kt#L9 
userLoginId dla każdego konta Fakelog jest taki sam i stąd wynika błąd z duplikowaniem ogłoszeń
Czekam na odpowiedź @mklkj
