### ISSUE TITLE
Wulkanowy nie wyświetla danych w zakładce Dostęp Mobilny

### ISSUE THREAD

**Issue by Zaptyp** [wulkanowy/wulkanowy#1879]
## Co powinno się dziać
Wulkanowy powinien wyświetlać dane w zakładce Dostęp Mobilny

## Co się dzieje
Wulkanowy nie wyświetla danych w zakładce Dostęp Mobilny
![image](https://user-images.githubusercontent.com/43276401/171433776-cafb34e0-2ab2-4ca4-acb3-5bb0f970281b.png)
![image](https://user-images.githubusercontent.com/43276401/171433805-fe284cad-6d4e-49f2-b681-517fcb33d062.png)

## Jak to zrobić kolejny raz:
Poruszone na discordzie
https://canary.discord.com/channels/390889354199040011/499273409306427406/979481996596228117
## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: 1.6.4
  - Wersja Androida: 11
  - Adres URL dziennika: vulcan.net.pl/zielonagora

**Comment by Zaptyp** [comment]
`{"data":[{"NazwaUrzadzenia":"Redmi Note 8T","DataUtworzenia":"2022-05-25 12:01:20","DataModyfikacji":"2022-05-25 12:01:49","IdentyfikatorUrzadzenia":"B582015C-91E1-4F08-965D-BE50A284CA44","Id":-38006},{"NazwaUrzadzenia":"Szkolny.eu moto g(8) power - nie usuwać","DataUtworzenia":"2022-04-14 17:49:11","DataModyfikacji":"2022-04-14 17:49:16","IdentyfikatorUrzadzenia":"-1","Id":-37054}],"success":true}`

**Comment by Zaptyp** [comment]
@mklkj

**Comment by Faierbel** [comment]
[JSON.txt](https://github.com/wulkanowy/wulkanowy/files/8923399/JSON.txt)
@mklkj

**Comment by mklkj** [comment]
@Faierbel w późniejszej konwersacji okazało się, że problem dotyczy wyłącznie kont rodzica i nie ma nic wspólnego z treścią jsona
