### ISSUE TITLE
Wulkanowy wysyła puste powiadomienia z ocenami końcowymi

### ISSUE THREAD

**Issue by Zaptyp** [wulkanowy/wulkanowy#1881]
## Co powinno się dziać
Wulkanowy nie powinien wysyłać powiadomienia o ocenach końcowych gdy ich nie ma 

## Co się dzieje
Wulkanowy wysyła puste powiadomienia o ocenach końcowych 
![image](https://user-images.githubusercontent.com/43276401/171436368-2dd2d10c-4a4f-4485-a579-9b91f24e8ed8.png)
![image](https://user-images.githubusercontent.com/43276401/171436396-d0762891-3af9-4548-b5fe-23b6fe66e241.png)

## Jak to zrobić kolejny raz:
Bug zgłoszony na discordzie:
https://canary.discord.com/channels/390889354199040011/639463026881200128/974427655782957066
## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: DEV 7631
  - Wersja Androida: 12
  - Adres URL dziennika: edu.gdansk.pl

**Comment by mklkj** [comment]
Używasz dość starego DEVa. Ten błąd powinien zostać naprawiony już jakiś czas temu. Zaktualizuj apkę do 7683
