### ISSUE TITLE
Widok sal lekcyjnych

### ISSUE THREAD

**Issue by thisfamousdev** [wulkanowy/wulkanowy#2017]
Taki widok jest przydatny szczególnie gdy dodane są zastępstwa

**Comment by mklkj** [comment]
Hej @thisfamousdev. Możesz dokładniej opisać co masz na myśli? Przypominamy tylko, że jesteśmy ograniczeni do tego, co da się wyciągnąć z dziennika :)

**Comment by mklkj** [comment]
Chyba nie rozumiem. Możesz to rozrysować?

**Comment by mklkj** [comment]
@thisfamousdev możesz dołączyć do naszego discorda https://discord.gg/vccAQBr i tam wysłać :)

**Comment by mklkj** [comment]
Chyba już wiemy o co chodzi. Wulkanowy pokazuje numery sal wtedy, gdy taka informacja pokazuje się na stronie www dziennika UONET+. Wygląda na to, że ostatnia aktualizacja systemu UONET+ coś zepsuła i przez to sale przestały się wyświetlać. Po stronie Wulkanowego nic z tym nie zrobimy
