### ISSUE TITLE
Wulkanowy pokazuje złą datę wydania wersji

### ISSUE THREAD

**Issue by kittyra** [wulkanowy/wulkanowy#2023]
## Co powinno się dziać
Powinno pokazywać prawidłową datę wydania wersji 1.7.5.

## Co się dzieje
Pokazuje złą datę wydania wersji.
https://i.ibb.co/Rgv6wNJ/Screenshot-20221026-223501-Wulkanowy-1.png

## Jak to zrobić kolejny raz:

 Wejdź w ustawienia i o aplikacji

## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: 1.7.5 (f-droid)
  - Wersja Androida: 12

**Comment by mklkj** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12111

**Comment by mklkj** [comment]
Nowe apk jest [już dostępne](https://gitlab.com/fdroid/fdroiddata/-/commit/7e547a6cb2e5d8b53540152b5a64ba06a3e81d31#bbc6dd51ef1c9a1b75659ac08b906d49caf0623b_29808_29828) w repo fdroida i [na tej wersji](https://f-droid.org/repo/io.github.wulkanowy_115.apk) jest już poprawna data zbudowania apki (2022-11-18)
