### ISSUE TITLE
Kotlin multiplatform do IOSa i Androida?

### ISSUE THREAD

**Issue by robalmeister** [wulkanowy/wulkanowy#2038]
https://kotlinlang.org/lp/mobile/ myślę że tu będzie najmniej przepisywania na iOSa 🤔

**Comment by mklkj** [comment]
W zasadzie to od momentu kiedy o KMM zaczęto mówić to myślimy o użyciu tej technologi do zrobienia portu Wulkanowego na iOS.

Problemem są tu jednak biblioteki, z których aplikacja/sdk korzysta. Np. scraper mamy napisany w Jsoup/jspoon + okhttp/retrofit, gdzie żadna z tych bibliotek nie jest multiplatformowa. Na chwilę obecną zastąpienie jsoupa na iOS wymagałoby użycia np. SwiftSoup, ale nie widziałem gotowego wrappera na obie te biblioteki, więc musielibyśmy zrobić to sami, co już jest sporym wyzwaniem. Okhttp i retrofita można byłoby zastąpić ktorem, ale to ciągle sporo pracy.

Ogólnie nie mówimy nie, ale ciężko powiedzieć, czy to się kiedykolwiek stanie :) Niestety największym wrogiem jest brak czasu

**Comment by mklkj** [comment]
Related #249

**Comment by robalmeister** [comment]
Ale można requesty przez ktora

**Comment by mklkj** [comment]
Można, ale trzeba jakoś przepisać przy okazji interceptory (logowania i sprawdzające błędy są krytyczne) tak, żeby działały też na iOS. Co nie zmienia faktu, że to nie jedyna problematyczna pod tym względem biblioteka

**Comment by mklkj** [comment]
Nic nie wskazuje na to, że kiedykolwiek to zrobimy. Dla osób chcących nieoficjalnej aplikacji na iOS jest https://github.com/Vulcanova/Vulcanova
