### ISSUE TITLE
Możliwość wykluczenia ocen wyższych niż 6 przy obliczaniu średniej

### ISSUE THREAD

**Issue by Me-Phew** [wulkanowy/wulkanowy#2039]
Czasami w dzienniku pojawiają się wartości liczbowe nie będące ocenami (np. wynik procentowy egzaminu). Jeżeli nie zostanie im przypisana waga 0, średnia obliczana przez aplikację nie ma sensu.

**Comment by Zaptyp** [comment]
Średnia liczona nie jest przez aplikację ale przez dziennik no chyba że wymusisz liczenie w ustawieniach albo gdy twoja szkoła nie ma uruchomionego liczenia średniej to aplikacja liczy

**Comment by Me-Phew** [comment]
Faktycznie, przy wymuszonym liczeniu wyświetla się prawidłowa średnia, dzięki za pomoc
