### ISSUE TITLE
Zawiera reklamy w google play a w readme nie zawiera

### ISSUE THREAD

**Issue by robalmeister** [wulkanowy/wulkanowy#2050]
do fixu

**Comment by mklkj** [comment]
Faktycznie, zapomnieliśmy o tym dopisku. Na swoje usprawiedliwienie powiemy, że reklamy są całkowicie opcjonalne i jeśli nie chcesz to nie musisz ich oglądać

**Comment by robalmeister** [comment]
Nie wiem, czy zawiera reklamy powinny być wtedy gdy nie da się ich wyłączyć za pieniądze

**Comment by mklkj** [comment]
@Daxxxis poprawiłbyś w znanych ci językach? Wołam ciebie, bo znasz najwięcej z języków, w których jest README :)
