### ISSUE TITLE
Frekwencja i plan zajęć w weekend ( szkoła zaoczna )

### ISSUE THREAD

**Issue by Gomulsky** [wulkanowy/wulkanowy#2064]
Możliwość wyświetlania planu zajęć i frekwencji dla osób uczących się w szkołach weekendowych.

Ja sam uczęszczam do takiej i aplikacja pomija weekendy, wyświetlając tylko wpisy od poniedziałku do piątku.

**Comment by mklkj** [comment]
To fakt, apka nie wyświetla tych dni od razu, ale nadal da się do nich dostać. Wystarczy, że klikniesz między strzałką następny/poprzedni dzień - wtedy pokaże się kalendarz, w którym będziesz mógł wybrać dowolny dzień, w tym również sobotę i niedzielę. Nie jest to idealne rozwiązanie, ale informuję o nim, bo w końcu jest już dostępne i dobrze żebyś o nim wiedział
