### ISSUE TITLE
Zmiana z Groovy DSL na Kotlin DSL

### ISSUE THREAD

**Issue by robalmeister** [wulkanowy/wulkanowy#2075]
kod jest napisany w kotlinie, jutro walne pulla z ktsem

**Comment by mklkj** [comment]
jakieś uzasadnienie? Nie widzę sensu ani potrzeby tej zmiany

**Comment by robalmeister** [comment]
Myślę, że warto:
https://blog.gradle.org/kotlin-meets-gradle

**Comment by mklkj** [comment]
Mamy obecnie całe 6 plików w groovym https://github.com/wulkanowy/wulkanowy/search?l=Gradle, gdzie jeden plik (sonarqube.gradle) jest obecnie nieużywany, dwa są ekstremalnie krótkie, config jacoco jest raczej stały i nie zmienia się zbyt często, a ostatnie 2 zawierają głównie informacje o zależnościach. Nie mówię kategorycznie nie, ale nie wiem czy problemy (które występowały z obsługą tych plików w IDE jak ostatnio się bawiliśmy .kts) nie przewyższą zysków z tej zmiany.

@Faierbel?

**Comment by robalmeister** [comment]
sam gradle proponuję kotlin z ktsem

**Comment by Faierbel** [comment]
Ostatni raz kiedy się bawiłem kotlinem w gradle to działało to tak sobie ale było to z rok ten. Możliwe że coś się poprawiło i jeśli faktycznie po przetestowaniu będzie wszystko działać to nie widzę przeciwwskazań

**Comment by bartekpacia** [comment]
Bardzo się poprawiło, KTS gituwa, polecam Wam.

100x lepiej się edytuje kod mając statyczne typy, IntellIj super podpowiada wszystko, miodzio.

**Comment by mklkj** [comment]
Kotlin DSL oficjalnie domyślnym w Androidzie https://android-developers.googleblog.com/2023/04/kotlin-dsl-is-now-default-for-new-gradle-builds.html

**Comment by mklkj** [comment]
W paru innych projektach używam .kts (razem z version catalogs) i moim zdaniem korzyści z tego nie mielibyśmy tutaj żadnej, tylko przepalilibyśmy na to czas
