### ISSUE TITLE
Wulkanowy wydłużył moją nazwę szkoły z 6 liter do 64 liter

### ISSUE THREAD

**Issue by Zaptyp** [wulkanowy/wulkanowy#2094]
Po aktualizacji 1.9.0 wulkanowy zaczął wydłużać moją nazwę szkoły jak wcześniej był napisany skrótem to teraz Wulkanowy dał pełną nazwę szkoły i kafelek nie potrafi czegoś takiego pokazać (bo tekst nie ładnie wychodzi po za kafelek)
![Screenshot_20230103-130505_W7978_feature_bottom-nav-order.png](https://user-images.githubusercontent.com/43276401/210355466-0f8f265e-27ad-4771-9f8c-603bc4739553.png)

**Comment by mklkj** [comment]
Zamiana skrótowej nazwy szkoły na pełną było celowe, ale oczywiście tekst nie powinien się tak nie-mieścić

**Comment by Zaptyp** [comment]
I to jeszcze występuje w sekcji dane ucznia

**Comment by Zaptyp** [comment]
![Screenshot_20230103-131822_W7978_feature_bottom-nav-order.png](https://user-images.githubusercontent.com/43276401/210355987-d30de32a-4d17-41c8-bad1-05dac85f0595.png)
