### ISSUE TITLE
Top app bar MD3

### ISSUE THREAD

**Issue by Daxxxis** [wulkanowy/wulkanowy#2148]
related #1660 
https://m3.material.io/components/top-app-bar/overview

- kolor app bara taki sam jak tło aplikacji
- "minimalizujący" się app bar przy przewijaniu

**Comment by mklkj** [comment]
Podchodząc realistycznie do tego - raczej tego nigdzie nie zaimplementujemy. A na pewno nie bez robienia większego redesignu, na który się nie zapowiada
