### ISSUE TITLE
Punkty za uwagi zawsze dają komunikat "brak danych"

### ISSUE THREAD

**Issue by folospior** [wulkanowy/wulkanowy#2195]
## Co powinno się dziać
Punkty ujemne jak też i dodatnie powinny być pokazywane po kliknięciu w uwagę w Wulkanowym.

## Co się dzieje
Punkty niezależnie od wpisnej wartości zawsze mają wpisane "Brak danych" w Wulkanowym. 
![Screenshot_20230509_230958](https://github.com/wulkanowy/wulkanowy/assets/111700958/8d250752-038a-49c9-a689-522cca0df43c)
![Screenshot_20230509_230843_Wulkanowy](https://github.com/wulkanowy/wulkanowy/assets/111700958/6bca852c-dc5d-4d1f-88c3-b2b6e1dc4406)

## Jak to zrobić kolejny raz:

  1.Kliknij na wpisaną uwagę z punktami wpisanymi przez nauczyciela.
  

## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: 2.0.0
  - Wersja Androida: 13

**Comment by mklkj** [comment]
@folospior Wulkanowy pobiera dane z innego miejsca niż oficjalna apka iiiii niezbyt nas interesuje co ona pokazuje :) Pokaż co jest na stronie www dziennika, bo mamy tylko te dane, które na www są dostępne

**Comment by mklkj** [comment]
Rozumiem, że na stronie www dziennika jest tak samo. Jeśli się mylę - otwórz ten issue ponownie
