### ISSUE TITLE
Pull to refresh na dashboardzie nie zawsze znika 

### ISSUE THREAD

**Issue by mklkj** [wulkanowy/wulkanowy#2206]
> Urządzenie: samsung SM-A137F
> Wersja SDK: 31
> Wersja aplikacji: 2.0.3-play
> Treść zgłoszenia:
> Koło odświeżania się blokuję i nie chce odświeżyć tej strony a gdy przejdę na inne strony to już odświeża normalnie

**Comment by folate** [comment]
s/swipe/pull

**Comment by mklkj** [comment]
Wydaje się, że nie ma już tego problemu. Możliwe, że naprawione w #2395, w sdk albo gdzieś indziej/wcześniej
