### ISSUE TITLE
Poprawa wyświetlania ocen proponowanych/przewidywanych

### ISSUE THREAD

**Issue by tadekdudek** [wulkanowy/wulkanowy#2232]
** Czy Twoja prośba o funkcję jest związana z problemem? Proszę opisz.**
Niektórzy nauczyciele zamiast normalnie dodać ocenę proponowaną robią coś takiego:
![oceny-proponowane](https://github.com/wulkanowy/wulkanowy/assets/99012892/acbcb231-ce8b-43c8-bd30-0792db923bb9)
Co oczywiście skutkuje syfem w ocenach proponowanych.

** Opisz żądane rozwiązanie **
Można by było przenosić tak dodane oceny do karty podsumowania. Nie widzę lepszego rozwiązania niż zwyczajne sprawdzanie po nazwie i wadze. Nie jest to na pewno najlepsze rozwiązanie, ale i tak było by to lepsze niż nic.

** Opisz alternatywy, które rozważałeś **
-

** Dodatkowy kontekst **
-

**Comment by mklkj** [comment]
To wygląda na bardzo ale to baaaardzo specyficzny przypadek, nie wiem czy chcemy to jakoś dodatkowo obsługiwać w apce, bo jeśli zrobimy to źle to zrobi się okrutny bałagan
