### ISSUE TITLE
Uczeń na tle klasy

### ISSUE THREAD

**Issue by rutra8002** [wulkanowy/wulkanowy#2318]
punkty są pokazywane jako procent, np
mam 6 punktów, klasa ma średnio 5, i pokazuje mi 6%, a klasie 5%, 
można dodać opcje wyświetlania tego jako procent, lub jako pkt

**Comment by mklkj** [comment]
@rutra8002 mógłbyś pokazać jak to wygląda aktualne w Wulkanowym a jak na stronie www dziennika?

**Comment by rutra8002** [comment]
![IMG_20231001_192631.jpg](https://github.com/wulkanowy/wulkanowy/assets/96191787/0362e7b2-5fbd-47ed-a1ed-d37eae96d267)

![IMG_20231001_192856.jpg](https://github.com/wulkanowy/wulkanowy/assets/96191787/766b8c9a-367b-4985-ae2e-51278a9b8670)

**Comment by rutra8002** [comment]
Pierwsze zdjecie to wulkanowy, drugie to strona

**Comment by rutra8002** [comment]
Duzo to nie zmienia, ale czasami można byc nieco confused przez ten %
