### ISSUE TITLE
Symulacja dzwonka

### ISSUE THREAD

**Issue by tadekdudek** [wulkanowy/wulkanowy#2323]
** Opisz żądane rozwiązanie **

Żeby trudniej było przegapić dzwonek przydałoby się powiadomienie chwilę przed i wtedy kiedy jest dzwonek, dobrze by było, gdyby do tego była wibracja

** Opisz alternatywy, które rozważałeś **

Teoretycznie można sobie ustawić tak alarmy, ale to jest niewygodne

**Comment by mklkj** [comment]
@tadekdudek mamy już rozwiązanie, które możesz dostosować do tych wymagań. Wejdź w Więcej -> Powiadomienia -> Pokazuj powiadomienia o nadchodzących lekcjach. Ta opcja domyślnie wysyła powiadomienia "ciche" (bez dzwonka i wibracji). Możesz to zmienić klikając w "Otwórz systemowe ustawienia powiadomień" i tam odszukując kanał o nazwie "Nadchodzące lekcje". Tam już możesz ustawić wibracje/dźwięk dzwonka według swojego widzimisię. 

Otwórz ticket ponownie jeśli to z jakiegoś powodu nie spełnia twoich oczekiwań
