### ISSUE TITLE
Dodatkowe lekcje widoczne w planie

### ISSUE THREAD

**Issue by krzyk** [wulkanowy/wulkanowy#2335]
Warto by było dodać opcję wyświetlania dodatkowych zajęć bezpośrednio w planie lekcji (pewnie z jakąś ikonką/kolorem) - bo zazwyczaj są to zajęcia planowane i mają większy sens w planie lekcji a nie w oddzielnej zakładce.

**Comment by mklkj** [comment]
W Wulkanowym mamy już takie coś, nazywa się to "Dodatkowe lekcje" i jest pod przyciskiem na górnym pasku w planie lekcji. Co do drugiej rzeczy - to prawda, wiele już mieliśmy takich zgłoszeń

**Comment by krzyk** [comment]
A rzeczywiście, teraz znalazłem, to zamienie opis i tytuł by był bardziej odpowiedni do drugiego problemu.
