### ISSUE TITLE
Plan lekcji czasami nie wyświetla numeru sali przy zastępstwach

### ISSUE THREAD

**Issue by KonradowyPL** [wulkanowy/wulkanowy#2349]
## Co się dzieje
Przy zastępstwach czasami nie wyświetla się numer sali. Dotyczy to planu w aplikacji, widgetu oraz funkcji powiadomień o nadchodzących lekcjach.

![](https://cdn.discordapp.com/attachments/1165617639893246024/1171851185779642429/image.png?ex=655e2e76&is=654bb976&hm=e50d1d4c2d3720ac89a733ae147f2f6728a219eabe46f5e0005511fb4d565bf3&)

Czasami, ponieważ mumer sali się nie wyświetla przy zastępstwie z historii oraz zaj. z wychowawcą, ale wyświetla się przy lekcji biologii

![](https://cdn.discordapp.com/attachments/1165617639893246024/1171852390123716638/image.png?ex=655e2f95&is=654bba95&hm=524d99c8f91af18e3ff442db19ad98c12c6b8dd057e245ae682618f7c2653844&)

Przy wejściu w szczegóły lekcji numer sali jest przekreślony i jeżeli nie wyświetla się poniżej ni przekeślony to ten numer jest poprawny.

## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: 2.2.6-play (138), 2023-11-06
  - Wersja Androida: 11

**Comment by mklkj** [comment]
@KonradowyPL Wulkanowy jest ograniczony do tego, co dostaje ze strony www dziennika. Może tych danych po prostu nie ma na stronie? Pokaż zrzut ekranu stamtąd

**Comment by KonradowyPL** [comment]
Na stronie działa poprwanie.
![image 1](https://github.com/wulkanowy/wulkanowy/assets/106955367/868866aa-2a16-4cd5-8565-0d508929cf8b)
Zapomniałem dodać, że przekreślony numer sali we wszystkich przypadkach jest poprawny.

**Comment by KonradowyPL** [comment]
Jeżeli to pomoże, to tutaj jest odpowiedź API sformatowana dla pythona [Vulcan-Api](https://github.com/kapi2289/vulcan-api)
```python
Lesson(
	id=27424360,
	date=DateTime(timestamp=1699311600000, date=datetime.date(2023, 11, 7), time=datetime.time(0, 0)),
	time=TimeSlot(id=2, from_=datetime.time(8, 50), to=datetime.time(9, 35), displayed_time='08:50-09:35', position=2),
	room=LessonRoom(id=30, code='FIT'), teacher=Teacher(id=23, name='Grzegorz', surname='Pinkowski', display_name='Grzegorz Pinkowski'),
	second_teacher=None,
	subject=Subject(id=75, name='Wychowanie fizyczne', code='wf', position=132),
	event=None,
	changes=LessonChanges(id=1108661, type=2, separation=False),
	pupil_alias=None,
	group=TeamVirtual(id=346, shortcut='2/2', name='Grupa 2 z 2', part_type='kryterium'),
	visible=True
)

```
```python

ChangedLesson(
	id=1108661, 
	unit_id=1, 
	schedule_id=None,
	lesson_date=DateTime(timestamp=1699311600000, date=datetime.date(2023, 11, 7),
	time=datetime.time(0, 0)),
	note='',
	reason=None,
	time=None,
	room=LessonRoom(id=11, code='35'),
	teacher=Teacher(id=57, name='Joanna', surname='Suter-Chmielewska', display_name='Joanna Suter-Chmielewska'),
	second_teacher=None,
	subject=None,
	event=None,
	changes=LessonChanges(id=1108661, type=2, separation=False),
	group=None
)
```
(nie wiem czy to pomoże, jeśli Wulkanowy jest napisany w kotlinie)

**Comment by mklkj** [comment]
Z tego co widać na screenach z www to:

tę część interpretuję (tak jak wulkanowy) jako oryginalną lekcję:
<img width="200" src="https://github.com/wulkanowy/wulkanowy/assets/12243282/eb3882f3-4363-4dbb-9058-4fecd52fc403">


<br>
<br>
a tę jako jej zastępstwo:

<br>
<br>
<img width="200"  src="https://github.com/wulkanowy/wulkanowy/assets/12243282/a498391b-016e-46ad-8b08-1686c1715ed5">

Patrząc tylko na to ciężko wyrokować, w jakiej faktycznie sali ma się odbywać Historia. Jeśli w sali nr 35, to powinno to być napisane niżej, między "Historia" a nazwiskiem nauczyciela.

Dziwnie się robi jak popatrzy się na to, co dostaje Dzienniczek VULCAN (czyli to co wysłałeś z vulcan-api). Oryginalna lekcja WF ma coś takiego:
```
room=LessonRoom(id=30, code='FIT')
```
rozumiem, że "FIT" to nazwa sali?

Tymczasem lekcja na zastępstwie ma już
```
room=LessonRoom(id=11, code='35')
```
czyli 35 - salę, która na www wyświetla się jako ta oryginalna!

Jak dla mnie to błąd po stronie www dziennika i nie powinniśmy tego ruszać, bo możemy zrobić jeszcze większy bałagan. Należałoby to zgłosić VULCANowi
