### ISSUE TITLE
Nowe rodzaje powiadomień

### ISSUE THREAD

**Issue by kapi2289** [wulkanowy/wulkanowy#235]
## Opis
Dodać powiadomienia o zmianach w planie lekcji, ostrzegające przed sprawdzianami i zadaniami domowymi, oraz o nowych wpisach frekwencji (tak jak w Dzienniczku+). Powiadomienia o zmianach w planie mogłyby działać w taki sposób, że pierwsza synchronizacja całego tygodnia byłaby bez żadnych powiadomień, a przy każdej następnej synchronizacji aplilacja wykrywała i wysyłała powiadomienie o każdej zmianie.

## Dyskusja
Czy powiadomienia o zmianach w planie powinny przychodzić przy każdej zmianie, tylko przy zmianie w ciągu następnego tygodnia, czy tylko następnego dnia?

**Comment by VenomPCPL** [comment]
Myślę, że w ciągu następnego tygodnia lub ewentualnie tylko na drugi dzień.
Chociaż ja osobiście jestem za tym pierwszym.

Moim zdaniem bezsensu troszkę pokazywać jak wpiszą kazdą zmianę.

A może możliwość ustawienia?

**Comment by dominik-korsa** [comment]
Ja myślę, że zmiany w **planie lekcji** dzień przed po południu, a potem jeśli się od tego czasu coś zmieni to na bieżąco.
**Sprawdziany i zadania domowe** to myślę, że dzień przed domyślnie, ale możliwość zmiany w ustawieniach, oraz powiadomienie o nowo wpisanych na bieżąco (też możliwość ustawienia czy użytkownik tego chce)
A co do **wpisów frekwencji** to można zrobić na bieżąco o nieobecnościach i na przykład informowanie po tygodniu, albo jakoś tak o nieusprawiedliwionych

**Comment by dominik-korsa** [comment]
Też dobrze by było zadbać o to, żeby te mniej ważne powiadomienia (np. dodanie nowego sprawdzianu czy zmiana w planie) miały niższy priorytet (nie wydawały dźwięku).

**Comment by dominik-korsa** [comment]
#523

**Comment by doteq** [comment]
#574
