### ISSUE TITLE
Pojawianie sie sprawdzianu w planie lekcji

### ISSUE THREAD

**Issue by SEWONIX** [wulkanowy/wulkanowy#2353]
Uwazam ze dobrym pomyslem jest dodanie np sprawdzianow do planu lekcji, ze jest lekcja i pod nia np napis sprawdzian czy cos tego typu

**Comment by mklkj** [comment]
Wydaje mi się, że to prawie to samo co #1935

**Comment by SEWONIX** [comment]
O sorry faktycznie
