### ISSUE TITLE
Błąd w menu

### ISSUE THREAD

**Issue by VenomPCPL** [wulkanowy/wulkanowy#238]
## Co powinno się dziać

Po przytrzymaniu na pierwszą pozycje w menu powinien znikać efekt kliknięcia

## Co się dzieje

Po przytrzymaniu na pierwszy element menu efekt kliknięcia zostaje

## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: 0.6.6
  - Wersja Androida: 7.0
  - Adres URL dziennika: nie dotyczy

**Comment by kapi2289** [comment]
Bug jest związany z biblioteką, której używamy - [`AHBottomNavigation`](https://github.com/aurelhubert/ahbottomnavigation), ten błąd jest już tam zgłoszony (https://github.com/aurelhubert/ahbottomnavigation/issues/270). My niestety nie jesteśmy w stanie nic z tym zrobić.
