### ISSUE TITLE
Pytanie odnośnie przyszłości projektu

### ISSUE THREAD

**Issue by ChronoBrake** [wulkanowy/wulkanowy#249]
Witam czy zamierzacie kiedyś wypuścić port na IOS? Słyszałem o https://flutter.io/ podobno bardzo fajnie się pisze, jednocześnie program umożliwa na raz portowanie na androida i IOS'a. 
Oraz drugie pytanie czy zamierzacie dodać do aplikacji "stronę nauczyciela" w takim sensie, że Vulcan posiada oficjalną aplikację dla nauczycieli, ale jest ona tak nędzna, że można dodawać tylko aktualną lekcje. Pozdrawiam.

**Comment by RicomenPL** [comment]
Witaj
Niestety ale nie mammy w planach wypuszczenie aplikacji na iOS z kilku powodów. Pierwszym jest że aby użyć Fluttera musielibyśmy przepisać całą aplikację na co niestety nie mamy zbytnio czasu ani ludzi którzy mogliby przyśpieszyć ten proces. Drugim powodem jest brak zasobów finansowych ponieważ aby napisać i testować aplikację na iOS potrzebny jest sprzęt Apple którego nie posiadamy. Dodatkowo subskrypcja konta deweloperskiego w sklepie AppStore też kosztuje.
Co do aplikacji dla nauczycieli także nie planujemy takiej. Nasza aplikacja jest nieoficjalna i korzystamy tylko z zasobów udostępnionym nam jako uczniom i niestety nie mamy dostępu do dziennika nauczyciela.

**Comment by ChronoBrake** [comment]
Rozumiem, ale gdybyście kiedyś zmienili zdanie i pozyskali możliwość testowania na IOS to podsyłam fajne narzędzie stworzone przez Google Developers do portowania backendu z androida do ios'a.
https://developers.google.com/j2objc/
