### ISSUE TITLE
Integracja z kalendarzem

### ISSUE THREAD

**Issue by WcaleNieMisker** [wulkanowy/wulkanowy#2516]
Proponuję dodać inne kalendarze niż ten od Google. Chodzi o to żeby sobie wybrać aplikacje z kalendarzem do którego chcemy dodać wydarzenie (sprawdzian, kartkówkę itp.)

**Comment by mklkj** [comment]
Jeśli mowa o istniejącej funkcji, to już teraz to tak powinno działać. Jeśli masz zainstalowaną inną aplikację obsługującą dodawanie wydarzeń, to wcześniej zobaczysz taką wybieraczkę:
![share_9086841581495201556](https://github.com/wulkanowy/wulkanowy/assets/12243282/bb36dd23-ee3e-4f36-946f-2741488620dd)

**Comment by WcaleNieMisker** [comment]
Nie wyświetla się tak jak na obrazie, od razu przekierowuje do kalendarza Google

**Comment by mklkj** [comment]
A jaki inny kalendarz masz zainstalowany?

**Comment by WcaleNieMisker** [comment]
Proton Calendar

**Comment by mklkj** [comment]
No to u mnie też się nie pokazuje. Widocznie Proton Calendar nie obsługuje takowej funkcji https://developer.android.com/guide/components/intents-common#AddEvent. Jeśli tego potrzebujesz to zgłoś to Protonowi, my na to nic nie poradzimy
