### ISSUE TITLE
Brak uczniów do wyboru przy logowaniu

### ISSUE THREAD

**Issue by sadorowo** [wulkanowy/wulkanowy#2525]
## Co powinno się dziać
Powinna zostać wyświetlona lista uczniów. uprzedzając pytanie, dane logowania są na pewno poprawne.

## Co się dzieje
Uczniowie nie są wyświetlani

## Jak to zrobić kolejny raz:

  1. Wpisz e-mail i hasło
  2. Wybierz standardową metodę logowania
  3. Kliknij "Zaloguj się"

## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: v2.5.5
  - Wersja Androida: 14
  - Adres URL dziennika: https://uonetplus.vulcan.net.pl/powiatmyslenicki

## Screen
![Screenshot_20240424-075420_Wulkanowy](https://github.com/wulkanowy/wulkanowy/assets/97941280/161e55fa-aeae-4b3b-adb0-f6050fc02e92)

**Comment by mklkj** [comment]
@sadorowo zaktualizuj apkę, bo masz starą wersję
