### ISSUE TITLE
Niepoprawny link w README

### ISSUE THREAD

**Issue by krisso-rtb** [wulkanowy/wulkanowy#2529]
Sekcja "Zbudowane za pomocą" ma na pierwszym miejscu 
`[Wulkanowy SDK](https://github.com/wulkanowy/sdk)`
który daje 404...
Gdzie się podziało tamto repo?

**Comment by krisso-rtb** [comment]
Jak to w takim razie działa?
Kto jest właścicielem czego? (przydałaby się jakaś krótka notatka w README)
W szczególności jest jest ownerem `sdk` ?

Bo nie bardzo rozumiem zwrot
```VULCAN nie podejrzał zmian w ich SDK```
Tu jest jakaś "trzecia strona"?

Nawet jeśli SDK zostało oznaczone jako prywatne, to chyba dalej można reverse-engineeringiem podejrzeć faktyczne zmiany?

**Comment by krisso-rtb** [comment]
Może niejasność zrozumienia zwrotu
```VULCAN nie podejrzał zmian w ich SDK```
wynika z jakieś mniej oczywistej struktury, kto kogo reprezentuje.
Jeśli jesteś z Wulkanowego, to zamiast `ich SDK` spodziewałbym się zwrotu `naszego SDK` :)

**Comment by tomaszk8266** [comment]
Jest jeszcze izzyondroid

**Comment by tomaszk8266** [comment]
Moim zdaniem zamknięcie sdk da niewiele, bo jak często widać każda mała aktualizacja vulcana wszystko psuje, pozwoli to tylko wyeliminować elementy wycelowane w wulkanowego.

**Comment by krisso-rtb** [comment]
Można by spróbować wydzielić do prywatnego repo tylko ten kawałek, który obchodzi blokadę Vulcana, a w publicznym repo trzymać pozostałą część (zapewne ponad 90%).

**Comment by tomaszk8266** [comment]
Widać jeden z tych właśnie pomysłów przyszedł im właśnie do głowy... W apce wyskakują błędy, strona działa. Na moje oko wygląda to tak samo jak wyglądałoby po aktualizacji dziennika.

`io.github.wulkanowy.sdk.scrapper.exception.VulcanException: A public action method 'Get' was not found on controller 'Vulcan.Efeb.Uczen.Web.Controllers.Api.PlanZajec.PlanZajecController'.
	at io.github.wulkanowy.sdk.scrapper.interceptor.ErrorHandlerTransformerKt.handleErrors(ErrorHandlerTransformer.kt:23)
	at io.github.wulkanowy.sdk.scrapper.repository.StudentRepository.getTimetable(StudentRepository.kt:195)
	at io.github.wulkanowy.sdk.scrapper.repository.StudentRepository$getTimetable$1.invokeSuspend(StudentRepository.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
`

**Comment by krisso-rtb** [comment]
Z tego co się orientuję, to Vulcan to nie tylko dziennik, ale też system płacowo-kadrowy-rozliczeniowy, więc szkoły z niego korzystające są w praktyce uwiązane.
Żaden dyrektor nie zgodzi się na używanie dziennika X i modułów kadrowo-płacowych Y, skoro może mieć pakiet all-in-one.

**Comment by tomaszk8266** [comment]
>Z tego powodu VULCAN na tym traci
Co właściwie (oprócz dobrej reputacji) traci?

**Comment by Oreeeee** [comment]
> Czasami zastanawiam się czy nie lepiej napisać jakiś open source dziennik, który każda szkoła mogłaby postawić na swoim serwerze, a następnie zachęcić szkoły do korzystania z niego

Przekonaj rządowe instytucje do korzystania z programu napisanego przez 3 gości ukrywających się za pseudonimem w piwnicy którzy nic z tego nie mają, zamiast programu napisanego przez "profesjonalną" firmę będącą od 30 lat na rynku z zarejestrowaną działalnością i płatnymi pracownikami .

**Comment by tomaszk8266** [comment]
Trochę nie rozumiem sensu #2550... W [app.js](https://uonetplus-uczen.vulcan.net.pl/Scripts/Vulcan.Efeb.Opiekun/24_4_3_58698/app/app.js) UUID są podane jak na tacy (o czym twórcy aplikacji zdają się wiedzieć, obrazek w poście na facebooku to właśnie jego fragment), można je wyciąć np. regexem, po co więc brać je z własnego API? SDK jest zamknięte, więc vulcan nie mógłby podejrzeć jak Wulkanowy to robi. Chyba że właśnie to chcecie zrobić po stronie własnego API, żeby opublikować SDK. Jeśli vulcan nie zbanuje was po IP, to byłby to krok w dobrą stronę.

**Comment by Faierbel** [comment]
Wyciąganie z app.js jest dużo mniej bezpieczne i bardziej podatne na zmiany Vulcana. Dostarczając mapping do SDK z naszego API mamy większą kontrolę nad tym jaki dokładnie endpoint użyje SDK. Oczywiście Vukcan może zawsze zrobić jakieś inne blokady ale to już rozmowa i działanie na inny czas.

**Comment by tomaszk8266** [comment]
Ok, dzięki za wyjaśnienie

**Comment by tomaszk8266** [comment]
Z tego co widzę w wersji dev w chuckerze mapping1.json jest pobierany przed każdym żądaniem do dziennika, nie byłoby lepiej to przechowywać i pobierać tylko przy błędzie?

**Comment by Faierbel** [comment]
@tomaszk8266 używasz najnowszej wersji? bo z tego co widze po logach mapping1.json pobieramy tylko razy podczas startu aplikacji. Stara wersja dev pobierała przed każdym żadaniem.

**Comment by tomaszk8266** [comment]
Musiałem mieć starego deva, sory

**Comment by tomaszk8266** [comment]
A może by tak opublikować jakąś archaiczną wersję SDK do eksperymentów? v****n (chodzi o tą firmę o której mówić nie można xd) by nie miał jak z tego skorzystać, a ludzie żądni przygód byliby szczęśliwi.

**Comment by MZPL** [comment]
Bardzo mi ta sytuacja przypomina walkę YT z adblockami - jeśli wulkanowy będzie się często psuć to ostatecznie zwykli użytkownicy przejdą na oficjalną aplikacje, o co vulcanowi chodzi. Pytanie tylko, dlaczego?

**Comment by Oreeeee** [comment]
Myślę że najlepiej jest skończyć #2399, to im trochę utrudni blokady bo będą też musieli kazać aktualizować swoją aplikację zamiast robić zmiany na frontendzie których użytkownik końcowy nie zauważy

**Comment by tomaszk8266** [comment]
>Głupi nie są. Będą widzieli, że opublikowana wersja jest starsza, niż wersja tego SDK, które jest wpychane w commity przy aktualizacji.

Chodzi mi o opublikowanie starej wersji po to, żeby mieć szkielet do modyfikacji. Co do tego że v****n radzi sobie bez kodu sdk - gdyby mieli do niego dostęp, byłoby jeszcze więcej modyfikacji wycelowanych w Wulkanowego a.k.a. "blokad" (mogliby modyfikować stronę tak, żeby psuć obsługę błędów Wulkanowego, tak jak zrobili to na początku, jest to chyba łatwiejsze od np. zmiany wszystkich endpointów).

> Bardzo mi ta sytuacja przypomina walkę YT z adblockami - jeśli wulkanowy będzie się często psuć to ostatecznie zwykli użytkownicy przejdą na oficjalną aplikacje, o co vulcanowi chodzi. Pytanie tylko, dlaczego?

Właśnie, dlaczego? Co im to właściwie da?

**Comment by tomaszk8266** [comment]
> Myślę że najlepiej jest skończyć #2399, to im trochę utrudni blokady bo będą też musieli kazać aktualizować swoją aplikację zamiast robić zmiany na frontendzie których użytkownik końcowy nie zauważy

Gdyby jakaś stara wersja sdk była publiczna, mogliby się tym zająć też inni, nie tylko członkowie organizacji, którzy na chwilę obecną mają na głowie ważniejsze sprawy (a mianowicie przywrócenie eduone)

**Comment by MZPL** [comment]
> Myślę że najlepiej jest skończyć #2399, to im trochę utrudni blokady bo będą też musieli kazać aktualizować swoją aplikację zamiast robić zmiany na frontendzie których użytkownik końcowy nie zauważy

Tylko szkoda, że nie będzie wtedy "Uczeń na tle klasy" w aplikacji. Z tego co wiem dalej nie zostało dodane to do API, no chyba że będzie dodatkowo scrapowane.

**Comment by tomaszk8266** [comment]
W repo SDK to było nazwane "trybem hybrydowym"

**Comment by tomaszk8266** [comment]
Jak właściwie działa moduł wiadomości i dlaczego cały czas się psuje? Adresy endpointów api są schowane w main.prodbundle_xx_x_x_xxxxx.js i są zmieniane jak mi się zdaje okresowo, więc dlaczego mapping nie wystarcza?

**Comment by mklkj** [comment]
wymagany jest nagłówek V-Token, do którego obliczenia potrzebny jest apiKey, który jest obfuskowany na coraz dziwniejsze sposoby

**Comment by tomaszk8266** [comment]
Czy apiKey nie jest stały/zmieniany okresowo? Dzisiaj logowałem się kilka razy i cały czas był taki sam...
