### ISSUE TITLE
Zakładka "Dostęp mobilny" nie działa

### ISSUE THREAD

**Issue by tomaszk8266** [wulkanowy/wulkanowy#2552]
## Co się dzieje
Urządzenia są wyświetlane poprawnie, ale nie można nic dodać, wyskakuje komunikat "Wystąpił nieoczekiwany błąd"

## Jak to zrobić kolejny raz:

  1. Przejść do zakładki "Dostęp mobilny"
  2. Urządzenia są wyświetlane poprawnie, usuwania działa
  3. Spróbować coś dodać. "Wystąpił nieoczekiwany błąd"

## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: 2.6.5-play
  - Wersja Androida: 14
  - Adres URL dziennika: uonetplus.vulcan.net.pl

**Comment by mklkj** [comment]
uonetplus-uczen czy uonetplus-uczenplus?

**Comment by tomaszk8266** [comment]
uonetplus-uczen

**Comment by tomaszk8266** [comment]
Jak teraz patrzę w wersji dev na żądania, które wulkanowy wysyła to widać tam tylko requesta do endpointa od już zarejestrowanych urządzeń, ten do rejestracji nowego urządzenia już nie

**Comment by tomaszk8266** [comment]
W 2.6.8 już działa, zamykam
