### ISSUE TITLE
Dynamiczne argumenty dla scraperów

### ISSUE THREAD

**Issue by cooligus** [wulkanowy/wulkanowy#2575]
## Czy Twoja prośba o funkcję jest związana z problemem? Proszę opisz.
Głównie o co się rzucają te małe dziadygi w opiniach, to o częste aktualizację, które nie pomagają

## Opisz żądane rozwiązanie
Te całe UUID zamiast hardcodować to wysyłać z serwera (tak jak te admin komunikaty). Mam szczerą nadzieję, że jest to możliwe

**Comment by tomaszk8266** [comment]
Wulkanowy już pobiera UUID z mappingu (czyli z serwera), nie są hardcodowane w aplikacji. Ostatnie aktualizacje naprawiały tylko wiadomości (a dokładniej pobieranie apiKey potrzebnego do policzenia v-tokena).

**Comment by cooligus** [comment]
A to kozacko w takim razie
