### ISSUE TITLE
Blokowanie wiadomości od poszczególnych osób

### ISSUE THREAD

**Issue by sioodmy** [wulkanowy/wulkanowy#2576]
Powinniśmy dodać opcje zablokowania lub przynajmniej wyciszania powiadomień od poszczególnych osób na dzienniku. 

Niektórzy nauczyciele serio nie mają co robić tylko wypisywać wiadomości na dzienniku generując zbędne powiadomienia.

Na dniach moge zrobic PR z tym, tylko chciałbym usłyszeć jakiś feedback odnośnie samego pomysłu

**Comment by mklkj** [comment]
Istnieje już taka funkcja. Poszukaj :)
