### ISSUE TITLE
Aplikacja crashuje się klikając zakładkę "Wygląd i zachowanie" jeśli język jest ustawiony na kaszubski

### ISSUE THREAD

**Issue by playsenge** [wulkanowy/wulkanowy#2592]
## Co powinno się dziać
Tytuł. Nie powinno się crashować

## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: 2.6.16
  - Wersja Androida: 14 (OnePlus OxygenOS 14.0)
  - Adres URL dziennika: https://uonetplus.vulcan.net.pl/bydgoszcz

**Comment by mklkj** [comment]
Fixed in #2574 2574
