### ISSUE TITLE
Błąd z aktualizacją widżetu

### ISSUE THREAD

**Issue by popek069** [wulkanowy/wulkanowy#276]
## Co powinno się dziać
Plan powinien się sam aktualizować

## Co się dzieje
Zastępstwa aktualizują się dopiero kiedy zmienię dzień na widżecie i z powrotem na poprzedni. W aplikacji wszystko działa

## Jak to zrobić kolejny raz:

  1.
  2.
  3.

## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: 1907
  - Wersja Androida: 9.0
  - Adres URL dziennika: nie dotyczy

**Comment by RicomenPL** [comment]
Sprawdź wersję 0.7.0 Jeśli problem będzie nadal to napisz.

**Comment by RicomenPL** [comment]
Błąd został naprawiony w wersji 0.7.0. Jeśli nadal on występuje otwórz ponownie issue.
