### ISSUE TITLE
Dodanie średniej z całego roku szkolnego

### ISSUE THREAD

**Issue by TechniKris** [wulkanowy/wulkanowy#291]
U mnie w szkole średnia na koniec roku szkolnego jest liczona z ocen z obu półroczy (tzw
 średnia roczna). Przydatna była by więc możliwość przełączenia średnich z _1. semestr/2. semestr_ na _śródroczna/roczna_.

Tu fragment z naszego WZO
![Screenshot_20190322-092920_Adobe_Acrobat](https://user-images.githubusercontent.com/30842158/54810931-9aa03f80-4c87-11e9-9091-f322ee591747.png)

**Comment by RicomenPL** [comment]
Kilka osób też już nam zgłaszało taką potrzebę, więc taka funkcja zostanie zaimplementowana w kolejnych wersjach
