### ISSUE TITLE
Problem z zmianą konta 

### ISSUE THREAD

**Issue by MrTomek** [wulkanowy/wulkanowy#309]
## Problem z przełączaniem konta

![55560351_793132394399701_3156395238474383360_n](https://user-images.githubusercontent.com/13391813/55167977-41964700-5172-11e9-996e-47c852f82026.jpg)

Mam zalogowane konto dwa różne konta, z których jedno to konto rodzica a drugie konto ucznia, oba z nich są ustawione na te samego ucznia. 
Różnica nie jest istotna przy  ocenach czy planie lekcji, lecz ważne jest to przy wiadomościach.

## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: 0.7.3 (29)
  - Wersja Androida:  Android 6.0

**Comment by RicomenPL** [comment]
Dzięki za zgłoszenie!

Jeśli mógłbyś to zainstaluj tą wersję aplikacji
https://app.bitrise.io/artifact/13581556/p/9fe152458756560b4b55e01290bf5422

Zawiera ona poprawkę dla tego błędu. Nie musisz odinstalowywać wersji ze Sklepu Play. Wersja z linku będzie pod nazwą Wulkanowy DEV. 

Jeśli wszystko będzie działać to powiadom nas.
