### ISSUE TITLE
Brak zmiany danych po zmianie konta 

### ISSUE THREAD

**Issue by MrTomek** [wulkanowy/wulkanowy#316]
## Co się dzieje

Podczas przełączania konta (między uczniem a rodzicem) przełącza się choć jest potrzeba przeładowania wiadomości. Stawiam że reszta elementów też lecz przy koncie uczeń rodzic nie widać tego, gdyż posiadają one takie same dane w innych sekcjach.   

## Co powinno się dziać

Po przełączeniu konta powinno zaczytań dane z cache albo je automatycznie przeładować.
Wydaje mi się że samo wczytanie z cache będę odpowiednie, a przeładowanie dopiero gdy użytkownik tego chce (tak jak to normalnie jest za pomocą gestu). 

## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: 0.7.4 (30)
  - Wersja Androida: 6.0
  - Adres URL dziennika: resman Rzeszów

**Comment by RicomenPL** [comment]
Witaj

Czy mógłbyś bardziej opisać ten problem? Aktualnie aplikacja przy wejściu np w wiadomości sprawdza w lokalnej bazie danych czy już były wiadomości wcześniej pobrane. Jeśli nie to zaczyna je pobierać z internetu i zapisuje w bazie. Wszystko jest oparte na wartości studentId które pobieramy ze strony dziennika i w pewnych przypadkach np gdy zalogowany jest rodzic i uczeń na jednym telefonie mogą występować problemy. Dlatego prosimy o bardziej szczegółowy opis abyśmy mogli to naprawić.

**Comment by MrTomek** [comment]
Gdy jestem zalogowany na koncie ucznia i wejdę w wiadomości i je odzwierzęce wszystko wygląda poprawienie, po przełączeniu na konto rodzic widać ładnie animację przełączenia konta, gdy teraz wejdę w zakładce wiadomości wyświetlają się wiadomości ucznia dopiero gdy odzwierzęce pojawiają sie wiadomości rodzica. 

Oczywiście dziła to tak samo w drugą stronę gdy przełączam sie między rodzicam a uczeniem.
