### ISSUE TITLE
Informacja o wygaśnięciu sesji (zmiany hasła) dla wielu uczniów

### ISSUE THREAD

**Issue by dominik-korsa** [wulkanowy/wulkanowy#410]
## Co powinno się dziać

Jeśli rodzic (mający dwóch lub więcej dzieci na jednym koncie) zmieni hasło, kliknięcie Zaloguj się i wybranie uczniów powinno zaktualizować dane wszystkich uczniów.

## Co się dzieje

Po wprowadzeniu nowych danych i wyborze ucznia innego niż aktywnego w momencie pojawienia się informacji o wygaśnięciu sesji wyświetli się błąd `Uczeń jest już zalogowany`. Wymagane jest wtedy wylogowanie pozostałych uczniów i zalogowanie się ponowne.

## Jak to zrobić kolejny raz:

  1. Zalogować się w Wulkanowym na konto rodzica dodając dwóch lub więcej uczniów
  2. Zmienić hasło do dziennika
  3. Kliknąć zaloguj się ponownie w informacji o wygaśnięciu sesji
  4. Wporwadzić dane logowania
  5. Wybrać wielu uczniów

## Informacje o urządzeniu i Dziennik

  - Wersja aplikacji: **0.9.2**
  - Wersja Androida: **6.0.1**
  - Adres URL dziennika: **uonetplus.vulcan.net.pl**

**Comment by Faierbel** [comment]
Zrobione w #2386
