### ISSUE TITLE
Zmiana koloru aplikacji

### ISSUE THREAD

**Issue by HIRUS00107** [wulkanowy/wulkanowy#421]
Zmiana koloru aplikacji:
-Dodatkowa możliwość personalizacji,
-Inne kolory do wyboru zamiast czerwonego, fajnie byłoby, jakbyście dodali koło RGB,

A poza tym to świetna aplikacja i pozdrawiam dev team.

**Comment by Faierbel** [comment]
Witaj

Z góry przepraszam za tak późną odpowiedź. Nie planujemy takiej funkcji ze względu że może być to pracochłonne a aktualnie są ważniejsze funkcje do stworzenia.  Ale nie mówimy też nie więc jak wyjdzie wersja produkcyjna naszej aplikacji może uda nam się wprowadzić większe możliwości personalizacji.
