### ISSUE TITLE
Adaptacyjna data w widgecie planu lekcji

### ISSUE THREAD

**Issue by dominik-korsa** [wulkanowy/wulkanowy#483]
Proponuję, aby dodać w Wulkanowym funkcję adaptacyjnej zmiany daty w planie lekcji, która wyświetlała by domyślnie datę dzisiejszą, ale 30 minut po zakończeniu lekcji (lub w przypadku braku lekcji w planie po godz. 17:00) wyświetlała by się data jutrzejsza. To samo może być też zastosowane w innych widokach korzystających ze zmiany daty.

**Comment by Faierbel** [comment]
Myślę że to ciekawa funkcja którą dodatkowo można dodać w ustawieniach aby użytkownik mógł ją wyłączać i włączać i aby mógł zmienić ten czas po zakończeniu lekcji bo jakoś mi się wydaje za krótki. Ale funkcja godna dodania
