### ISSUE TITLE
Błąd parsowania szczęśliwego numerka

### ISSUE THREAD

**Issue by juby210-PL** [wulkanowy/wulkanowy#491]
## Co powinno się dziać

Powinien być parsowany szczęśliwy numerek

## Co się dzieje

Aplikacja próbuje parsować skrót nazwy mojej szkoły zamiast szczęśliwego numerka
![image](https://user-images.githubusercontent.com/31005896/64370073-fb48ec00-d01d-11e9-88db-a442fd1b610f.png)

## Jak to zrobić kolejny raz:

  1. Wejść w szczęśliwy numerek

## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: 0.9.4
  - Wersja Androida: 9.0
  - Adres URL dziennika: uonetplus.vulcan.net.pl

**Comment by Faierbel** [comment]
Witaj

Wczoraj wydaliśmy wersję 0.10.0 która powinna naprawić ten błąd, więc sprawdź czy masz aktualizację w Sklepie Play a jeśli nie to pobierz i zainstaluj apk z tego linka https://github.com/wulkanowy/wulkanowy/releases/download/0.10.0/43-1.apk. Jak problem nie zostanie rozwiązany to napisz abyśmy wiedzieli że coś jest nie tak.

**Comment by juby210-PL** [comment]
ok dzięki wszystko działa, nie miałem tylko aktualizacji w sklepie play
