### ISSUE TITLE
Przycisk powrotu z widoku logowania

### ISSUE THREAD

**Issue by dominik-korsa** [wulkanowy/wulkanowy#514]
Jeżeli użytkownik jest już zalogowany i dodaje kolejne konto nie ma widocznego sposobu opuszczenia widoku logowania. To mogło by być rozwiązane przyciskiem powrotu wyświetlanym tylko, jeśli nie ma żadnych dodanych kont.

Moim pomysłem jest przycisk http://materialdesignicons.com/icon/arrow-left w lewym, górnym rogu ekranu.

![image](https://user-images.githubusercontent.com/29484605/65384634-a77c1980-dd24-11e9-951f-6bdbe414338c.png)

**Comment by freshstudio** [comment]
A gestem/przyciskiem się nie da? Wątpię, że ktokolwiek by użył tej strzałki.

**Comment by Faierbel** [comment]
Da się przyciskiem Back ale strzałka też nie jest złym pomysłem

**Comment by Faierbel** [comment]
Guzik z tą strzałką nie spełnia te samej funkcji co guzik Back więc aktualna implementacja nawigacji jest poprawna.
