### ISSUE TITLE
Nie mogę się zalogować na Lubelski Vulkan.

### ISSUE THREAD

**Issue by Firemanpl** [wulkanowy/wulkanowy#573]
## Co powinno się dziać
Powinienem się zalogować.

## Co się dzieje
Nastąpiła zmiana adresu dostępu do vulkanu w Lublinie.

## Jak to zrobić kolejny raz:

  1.
  2.
  3.

## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: najnowsza
  - Wersja Androida: 10
  - Adres URL dziennika: https://logowanie.edu.lublin.eu

**Comment by dominik-korsa** [comment]
Dodaliśmy wsparcie dla tego dziennika w wersji *0.12.0*, którą można już pobrać z Google Play.

**Comment by mklkj** [comment]
#571 and released in https://github.com/wulkanowy/wulkanowy/releases/tag/0.12.0
