### ISSUE TITLE
Średnia klasy

### ISSUE THREAD

**Issue by xVemu** [wulkanowy/wulkanowy#625]
Proponuję aby dodać średnią klasy w zakładce KLASA.

**Comment by nixls** [comment]
Fajny pomysł, średnia mogłaby być wyliczana za pomocą liczby ocen z zakładki Uczeń na tle klasy

**Comment by mklkj** [comment]
Dziennik UONET+ wyświetla średnią ocen klasy z danego przedmiotu, ale tylko **jeśli pokazywanie średniej jest włączone** - w Wulkanowym (przynajmniej do teraz, wersja 0.14.2) ta informacja się nie wyświetla

Jeśli dziennik nie wyświetla średniej, nie możemy jej liczyć sami, bo średnia klasy jest średnią ważoną, a nie mamy informacji o wagach
