### ISSUE TITLE
doczytywanie danych niedostępnych przez api ze scrappera w trybie hybrid

### ISSUE THREAD

**Issue by selfisekai** [wulkanowy/wulkanowy#647]
niektóre dane nie są dostępne w API i fajnie by było gdyby aplikacja je jeszcze doczytywała ze scrappera jeśli nie są dostępne.

- [ ] kody rubryki ocen
- [ ] zaplanowana wcześniej lekcja w przypadku zastępstwa w planie lekcji

**Comment by mklkj** [comment]
Opisz dokładniej te rzeczy niedostępne w API

- przy każdej ocenie znajduje się pole `IdKategoria` a w słownikach znajduje się `KategorieOcen.Kod`, czy to nie jest ten kod rubryki?
- z planem lekcji jest już i tak kłopot, bo dzienniczek pokazuje lekcje w trochę inny sposób niż strona dziennika wyświetlając (z tego co wiem) na przykład z tym samym numerem lekcję odwołaną i niżej lekcję z zastępstwem
