### ISSUE TITLE
Jak się zalogować do apki?

### ISSUE THREAD

**Issue by JoelSalzesson** [wulkanowy/wulkanowy#653]
Skąd wziąć login i hasło?

**Comment by mklkj** [comment]
Witaj @JoelSalzesson 

Do Wulkanowego logujesz się używając tych samych danych logowania (para login/email i hasło) co do strony internetowej dziennika UONET+

**Comment by JoelSalzesson** [comment]
nie mam tam loginu ani hasła, rozumiem że to dla uczniów jest?

**Comment by mklkj** [comment]
Aplikacja jest przeznaczona wyłącznie dla uczniów i rodziców korzystających z dziennika UONET+

![](https://user-images.githubusercontent.com/12243282/72457364-b2245800-37c6-11ea-835a-1d7cd417d428.png)

**Comment by JoelSalzesson** [comment]
Chętnie przyłożę swoją rękę do tej apki ale nie jestem uczniem. Dajcie jakieś testowe credensziale.

**Comment by mklkj** [comment]
Do celów testowych używamy [Fake-loga](https://github.com/wulkanowy/fake-log).
Wystarczy, że przy logowaniu w aplikacji wybierzesz **Fakelog** a email i hasło uzupełni się *samo*
