### ISSUE TITLE
Usprawnienia do modalu przełączania między użytkownikami

### ISSUE THREAD

**Issue by terax6669** [wulkanowy/wulkanowy#691]
Nazwa szkoły różni się w zależności od metody, którą autoryzowaliśmy aplikację.

Po zalogowaniu przez API:

![image](https://user-images.githubusercontent.com/19204073/75383520-6213d780-58d4-11ea-89f0-1174249253b9.png)

Po zalogowaniu przez scraper:

![image](https://user-images.githubusercontent.com/19204073/75383540-6c35d600-58d4-11ea-902e-c66b455cae04.png)

Przy okazji, ten modal jest dość mały i przez to nieczytelny. Tekst po prostu się nie mieści, a nawet w landscape jego rozmiar pozostaje taki sam.

## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: 0.15.0
  - Adres URL dziennika: GPE

**Comment by dominik-korsa** [comment]
#671 to pomysł na dodanie wyboru użytkownika w menu More
