### ISSUE TITLE
Logowanie na wiele kont dot. tego samego ucznia

### ISSUE THREAD

**Issue by terax6669** [wulkanowy/wulkanowy#692]
## Co powinno się dziać

Aplikacja powinna prawidłowo zalogować się i przełączać pomiędzy kontami.

## Co się dzieje

Aplikacja wyświetla dwa **identycznie** wyglądające konta (w obu wyświetla się niestety imię ucznia).

Na pierwszy rzut oka po przełączeniu się między kontami lista urządzeń mobilnych pozostaje taka sama, więc wnioskuję że aplikacja w którymś miejscu zamiast na ID konta bazuje na ID ucznia jako unikalnym kluczu i właściwie to oba te konta działają teraz tak samo:

![image](https://user-images.githubusercontent.com/19204073/75384266-b7041d80-58d5-11ea-9a9d-6fd2284613b3.png)

![image](https://user-images.githubusercontent.com/19204073/75384283-bc616800-58d5-11ea-8c81-923bd449b43d.png)

## Jak to zrobić kolejny raz:

  1. Zaloguj się na konto dziecka.
  2. Zaloguj się na konto rodzica.

## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: 0.14.2, 0.15.0
  - Wersja Androida: 10 (security patch 2019-11-01) , MIUI 11.0.5
  - Adres URL dziennika: GPE

**Comment by mklkj** [comment]
To prawda, brakuje oznaczenia mówiącego o typie konta. Przełączanie między kontem ucznia a rodzica powinno jednak ogólnie działać - sprawdź na przykład w wiadomościach. Lista urządzeń rzeczywiście może nie przełączać się od razu - nasz błąd. Sprawdź jeszcze czy po ręcznym odświeżeniu lista urządzeń się zaktualizuje

**Comment by terax6669** [comment]
Pulldown rzeczywiście odświeża listę, na wiadomościach jest zauważalna różnica czyli przełączanie działa. :+1:

**Comment by mklkj** [comment]
Duplicate of #868
