### ISSUE TITLE
Can't log in if user's login page is not vulcan.net.pl

### ISSUE THREAD

**Issue by rnickson** [wulkanowy/wulkanowy#73]
I use UONET+ in opole territory, where we use uonetplus.eszkola.opolskie.pl/opole login address, and I can't log in to the app.

**Comment by mklkj** [comment]
Hi, thank you for using our app!

Try again using this syntax in the e-mail field: `https://eszkola.opolskie.pl\\user@host.com`

**Comment by rnickson** [comment]
@mklkj still not working (((((
> This password is incorrect
