### ISSUE TITLE
Powiadomienia przychodzą z dużym opóźnieniem

### ISSUE THREAD

**Issue by P4VL0** [wulkanowy/wulkanowy#760]
## Co powinno się dziać
Powiadomienia o wiadomościach przychodzą dużo później niź powinny. To samo oceny. 

## Co się dzieje
Powinny przychodzić natychmiastowo. Tak też jest w aplikacji dzienniczek+

## Jak to zrobić kolejny raz:

  1. Wiadomość/ocena musi przyjść na dziennik

## Informacje o urządzeniu i dzienniku

  - Wersja aplikacji: 0.17.0
  - Wersja Androida: 10
  - Adres URL dziennika: ?

**Comment by P4VL0** [comment]
btw:
optymalizacja beterii wyłączona,
dostęp do danych w tle zezwolony
Gmail pokazuje powiadomienia natychmiast. Lecz tu (mimo ustawienia 15minut odświeżania) apka reaguje duuużo później

**Comment by mklkj** [comment]
Może pokrótce opiszę w jaki sposób działają w tej chwili powiadomienia w Wulkanowym:
- wszystko opiera się na synchronizacji, podczas której pobierane są dane z dziennika, następnie porównywane z danymi zapisanymi lokalnie i na tej podstawie (jeśli będzie coś nowego w tych pobranych) wysyłane są powiadomienia. 
- synchronizacja jest wykonywana okresowo, domyślnie co godzinę.
- na niektórych urządzeniach (głównie Huawei, Xiaomi) są problemy z działaniem synchronizacji, bo producenci mają zbyt ostrą politykę zabijania aplikacji w tle

Dlaczego nie korzystamy z powiadomień push, tak jak Dzienniczek+?
Kiedy Wulkanowy powstawał, te powiadomienia w zasadzie nie działały (to był jeden z głównych powodów powstania Wulkanowego) i dlatego zdecydowaliśmy się na podejście do tematu w ten sposób

Z tego powodu powiadomienia nie mogą przychodzić natychmiast, bo to w obecnej sytuacji niemożliwe. Przy domyślnej synchronizacji cogodzinnej powiadomienia mogą mieć poślizg do godziny. Podobnie dla 15 minut opóźnienie powinno wynosić do 15 minut


Bierzemy pod uwagę obsługę powiadomień push jak w Dzienniczku+, ale wymaga to trochę zmian w aplikacji i nie wiemy kiedy udałoby się nam to ogarnąć

**Comment by MrBartusek** [comment]
@P4VL0 można by było przerobić to issue na feature request o dodanie lepszych powiadomień a nie bug repport?
