### ISSUE TITLE
‘Incognito mode’ dla wiadomości, czyli możliwość otwierania ich bez informowania o tym nadawcy

### ISSUE THREAD

**Issue by studzinskik** [wulkanowy/wulkanowy#795]
Tryb, który pozwoli na przeczytanie treści wiadomości bez informowania o tym osoby, która ją wysłała. Przydatne w trakcie edukacji zdalnej, gdy wszyscy wysyłają wszystko przez dziennik a uczniowi nie od razu się chce to wykonać, ale chciałby przynajmniej wiedzieć co ma zrobić. Można wywołać na przykład przez przytrzymanie/kliknięcie trzech kropek na wiadomości lub przełączać się pomiędzy normalnym a ukrytym przez coś w panelu wiadomości. Ewentualnie później w takim trybie możliwość oznaczenia wiadomości jako przeczytanej gdy uznamy, że nauczyciel może wiedzieć o tym że odczytaliśmy.

**Comment by PanTajemnic** [comment]
niewykonalne na wersji dziennika 20.09.0007.39687

**Comment by mklkj** [comment]
https://discord.com/channels/390889354199040011/558394066505826304/753643999117574294

**Comment by mklkj** [comment]
W module Wiadomości Plus (#1945) oznaczanie wiadomości jako przeczytanych jest opcjonalne.

Mało tego - dopiero #1960 automatycznie ustawia wiadomości jako przeczytane, bo w wersjach 1.7.0 - 1.7.2 oznaczanie jako przeczytane nie działa

**Comment by mklkj** [comment]
Na razie zamykam - funkcja "incognito mode" zrobiona, ale nie do końca według oryginalnego requestu. W razie pojawienia się dokładniejszej wizji - otworzyć ten issue ponownie
