### ISSUE TITLE
Personalizacja pozycji na bottom navie

### ISSUE THREAD

**Issue by Luncenok** [wulkanowy/wulkanowy#820]
Zmienienie kolejności przycisków z dolnego menu i z "więcej". Coś w stylu tak jak ma teraz "Dzienniczek VULCAN"
![Screenshot_20200521-145321_Dzienniczek VULCAN](https://user-images.githubusercontent.com/53345435/82561064-feb3e180-9b72-11ea-97d9-b2338eea71ae.jpg)

**Comment by dominik-korsa** [comment]
https://ptb.discordapp.com/channels/390889354199040011/520237802735009812/524552309758492675

**Comment by dominik-korsa** [comment]
https://youtu.be/CVC8HLAnY7M
