### ISSUE TITLE
App shortcuts – skróty po długim przytrzymaniu ikony aplikacji

### ISSUE THREAD

**Issue by JelNiSlaw** [wulkanowy/wulkanowy#887]
Przykładowe skróty (może być maksymalnie 5)
- Oceny
- Frekwencja
- Sprawdziany
- Plan lekcji
- Wiadomości
- Zadania domowe

**Comment by JelNiSlaw** [comment]
![shortcuts](https://user-images.githubusercontent.com/25802745/84836426-019cd780-b036-11ea-9992-8514db49b453.png)
https://developer.android.com/guide/topics/ui/shortcuts.html

**Comment by suchy2020** [comment]
Nie wiem czy skróty zostały opublikowane, aczkolwiek u mnie ich nie ma. 

![IMG_20200908_220900.jpg](https://user-images.githubusercontent.com/34921955/92523261-58264600-f220-11ea-9cb1-05907272a40a.jpg)![Screenshot_2020-09-08-22-08-23-077_io.github.wulkanowy.jpg](https://user-images.githubusercontent.com/34921955/92523264-59577300-f220-11ea-9c69-f58de19cfee3.jpg)![Screenshot_2020-09-08-22-08-13-414_com.android.vending.jpg](https://user-images.githubusercontent.com/34921955/92523267-5b213680-f220-11ea-9759-3c9536fa425e.jpg)

**Comment by mklkj** [comment]
@suchy2020 Skróty pojawią się prawdopodobnie w wersji 0.21.0 planowanej wstępnie na koniec września. PR wprowadzający je jeszcze nie został zmergowany #939
