### ISSUE TITLE
Pokazywanie grupy obok lekcji

### ISSUE THREAD

**Issue by Luncenok** [wulkanowy/wulkanowy#942]
Grupy nie widać dopóki się nie kliknie na lekcje co jest dosyć irytujące, więc można by było dać opcję w ustawieniach np. Pokaż grupę obok lekcji

**Comment by KcrPL** [comment]
Bump, ewentualnie może w zakładce `Plan lekcji` dodać jakiś switch, żeby można było zmienić między planem lekcji grupy a klasy.

**Comment by Luncenok** [comment]
Jest taki przełącznik w ustawieniach.

**Comment by mklkj** [comment]
Ten przełącznik działa tylko dla trybu mobilnego i hybrydowego, które są teraz niedostępne. W trybie scrapper (domyślnym) nie ma obsługi wielu grup
