### ISSUE TITLE
Powiadomienie o nadchodzących lekcjach wyświetla odwołane lekcje

### ISSUE THREAD

**Issue by mklkj** [wulkanowy/wulkanowy#980]
## Co się dzieje
Lekcje oznaczone jako odwołane pojawiają się w powiadomieniu o nadchodzącej lekcji

## Co powinno się dziać
Lekcje oznaczone jako odwołane nie powinny się pojawiać w powiadomieniu o nadchodzącej lekcji.

## Jak to zrobić kolejny raz:

  1. Mieć załadowany plan lekcji na np. tydzień do przodu
  2. Zmienić jakieś z załadowanych już lekcji na odwołane
  3. Poczekać do momentu, kiedy ta odwołana lekcja powinna się zacząć

Szczegóły techniczne:
Przy zapisywaniu planu lekcji w bazie danych i ustawianiu powiadomień są one filtrowane pod kątem lekcji odwołanych. Lekcje które najpierw nie były odwołane, a następnie plan lekcji się zmienił nie zostają usunięte z powiadomień

**Comment by Luncenok** [comment]
Również nie zostają usunięte zaplanowane powiadomienia w przód. tzn. jeżeli się wyłączy powiadomienia o nadchodzącej lekcji w ustawieniach to tylko aktualnie wyświetlane powiadomienie się usunie, reszta zostaje nie usunięta.
